dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.5.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.2.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
