dependencies:
  bme280:
    url: github.com/toitware/bme280-driver
    version: ^1.0.0
  bme680:
    url: github.com/nilwes/bme680
    version: ^1.3.0
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.5.0
  font_tiny:
    url: github.com/toitlang/pkg-font-tiny
    version: ^0.1.0
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.8.1
  morse:
    url: github.com/toitware/toit-morse
    version: ^1.0.2
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.2.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  pcf8574:
    url: github.com/xal88/TOIT_PCF8574
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  ringbuffer:
    url: github.com/Informaticore/toit-ringbuffer
    version: ^1.0.1
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.1.0
  ssd1306:
    url: github.com/toitware/toit-ssd1306
    version: ^1.5.2
